# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1431, 951)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(0, 0, 1431, 1011))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("Black.png"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.GIF_1 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_1.setGeometry(QtCore.QRect(400, 160, 441, 331))
        self.GIF_1.setText("")
        self.GIF_1.setPixmap(QtGui.QPixmap("spheres1_ai_improvisation_by_gleb.gif"))
        self.GIF_1.setScaledContents(True)
        self.GIF_1.setObjectName("GIF_1")
        self.GIF_2 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_2.setGeometry(QtCore.QRect(410, 540, 461, 171))
        self.GIF_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.GIF_2.setText("")
        self.GIF_2.setPixmap(QtGui.QPixmap("1d735ad8eee8350adc96d50e1421ee6d.gif"))
        self.GIF_2.setScaledContents(True)
        self.GIF_2.setObjectName("GIF_2")
        self.GIF_3 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_3.setGeometry(QtCore.QRect(410, 700, 421, 111))
        self.GIF_3.setText("")
        self.GIF_3.setPixmap(QtGui.QPixmap("coollogo_com-81931662.gif"))
        self.GIF_3.setScaledContents(True)
        self.GIF_3.setObjectName("GIF_3")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.pushButton_start.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(10, 60, 121, 41))
        self.pushButton_exit.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(990, 10, 121, 41))
        self.pushButton_chrome.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_youtube.setGeometry(QtCore.QRect(1140, 10, 121, 41))
        self.pushButton_youtube.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.pushButton_youtube.setObjectName("pushButton_youtube")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(1290, 10, 121, 41))
        self.pushButton_whatsapp.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.responsebox_text = QtWidgets.QLabel(self.centralwidget)
        self.responsebox_text.setGeometry(QtCore.QRect(1000, 160, 181, 41))
        self.responsebox_text.setStyleSheet("background-color:transparent;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius:none;\n"
"color: rgb(0, 197, 197);")
        self.responsebox_text.setObjectName("responsebox_text")
        self.time = QtWidgets.QTextBrowser(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(1260, 820, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setStyleSheet("background: Transparent;\n"
"border-radius: none;\n"
"color:white;\n"
"font-size:20px;")
        self.time.setObjectName("time")
        self.date = QtWidgets.QTextBrowser(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(1260, 880, 181, 51))  #
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(65)
        self.date.setFont(font)
        self.date.setStyleSheet("background: Transparent;\n"
"border-radius: none;\n"
"color:white;\n"
"font-size:20px;")
        self.date.setObjectName("date")
        self.responsebox_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.responsebox_box.setGeometry(QtCore.QRect(1000, 210, 411, 541))
        self.responsebox_box.setStyleSheet("background-color: rgb(13, 13, 13);\n"
""
"color:white;\n"
"font-size:16px;")
        self.responsebox_box.setObjectName("responsebox_box")
        self.chat = QtWidgets.QPushButton(self.centralwidget)
        self.chat.setGeometry(QtCore.QRect(1290, 160, 121, 41))
        self.chat.setStyleSheet("background-color: rgb(0, 231, 231);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 48, 48);")
        self.chat.setObjectName("chat")
        self.input_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.input_lineedit.setGeometry(QtCore.QRect(1000, 760, 279, 34))
        self.input_lineedit.setMaximumSize(QtCore.QSize(279, 34))
        self.input_lineedit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"MS Sans Serif\";\n"
"background-color: rgb(13, 13, 13);\n"
"")
        self.input_lineedit.setObjectName("input_lineedit")
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.pushButton_start.setText(_translate("JarvisUi", "START"))
        self.pushButton_exit.setText(_translate("JarvisUi", "EXIT"))
        self.pushButton_chrome.setText(_translate("JarvisUi", "Chrome"))
        self.pushButton_youtube.setText(_translate("JarvisUi", "YouTube"))
        self.pushButton_whatsapp.setText(_translate("JarvisUi", "WhatsApp"))
        self.responsebox_text.setText(_translate("JarvisUi", "Response Box"))
        self.chat.setText(_translate("JarvisUi", "CHAT "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
